version: "3.7"
services:
  db:
    image: mongo
    container_name: pcr-db
    restart: always
    expose:
      - "27017"
    volumes:
      - ./packages/db/data:/data/db
  server:
    build:
      context: ./packages/server/
      dockerfile: Dockerfile
    container_name: pcr-server
    restart: always
    links:
      - db
    depends_on:
      - db
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
  web:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    stdin_open: true
    container_name: pcr-web-dev
    restart: always
    ports:
      - "3000:3000"
    environment:
      PROXY_PORT: 4000
